import '../styles/globals.scss';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { appWithTranslation } from 'next-i18next';
import Layout from '@/components/layout/layout';

function App({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1' />
        <link
          rel='icon'
          href='/favicon.ico' />
      </Head>

      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default appWithTranslation(App);
